InfiniTensor/InfiniTensor

Makefile, include/core/graph_handler.h, include/cuda/cuda_unary.h, pyinfinitensor/src/pyinfinitensor/onnx.py, src/core/graph_handler.cc, src/ffi/ffi_infinitensor.cc, src/kernels/cpu/unary.cc, src/kernels/cuda/unary.cc, src/kernels/cuda/unary.cu, src/operators/gather.cc, src/operators/split.cc, test/kernels/cuda/test_cuda_gather.cc, test/kernels/cuda/test_cuda_unary.cc, test/operators/test_gather.cc, test/operators/test_split.cc
1. impl sqrt on CUDA
2. unary ops support arbitary shapes.
3. fix Operator of Split, Gather and ReduceMean
=> impl sqrt on CUDA

include/core/tensor.h, src/core/tensor.cc, src/kernels/cuda/unary.cc
cudnn activations (e.g. reLU) support ND-Tensor (N < 4).
=> cudnn activations support ND-Tensor

src/kernels/bang/cast.cc, test/kernels/bang/test_bang_cast.cc
=> fix: fix castType mlu

CMakeLists.txt, src/cuda/cuda_runtime.cc, src/kernels/cuda/clip.cu, src/kernels/cuda/element_wise.cu, src/kernels/cuda/extend.cu, src/kernels/cuda/unary.cu
Add debug mode macro in cmakelist.
=> Fix kernel arguments, add debug mode

Makefile, docs/INSTALL_GUIDE_CN.md, scripts/dockerfile/infinitensor_ubuntu_22.04.dockerfile, scripts/dockerfile/infinitensor_ubuntu_22.04_CUDA.dockerfile
This PR adds Docker support for running this project, and it primarily accomplishes the following tasks:
- Added the necessary `Dockerfile` for running the project on CPU environment.
- Added commands to the `Makefile` for convenient Docker startup.
- Added documentation in `docs/INSTALL_GUIDE_CN.md` explaining how to launch the Docker environment.
=> feat(env): add docker support.

include/cuda/cuda_expand.h, include/cuda/cuda_where.h, include/utils/broadcast_shape.h, src/kernels/cuda/expand.cc, src/kernels/cuda/expand.cu, src/kernels/cuda/where.cc, src/kernels/cuda/where.cu, test/kernels/cuda/test_cuda_where.cc
modified where.cu where.cc cuda_where.h from master
=> "modified where"

Makefile, include/core/tensor_base.h, pyinfinitensor/tests/test_api.py, pyinfinitensor/tests/test_onnx.py, src/ffi/ffi_infinitensor.cc
=> Copyout numpy接口

src/kernels/kunlun/softmax.cc, test/kernels/kunlun/test_kunlun_softmax.cc
=> Xpu task4 support: add softmax

Makefile, src/kernels/kunlun/all_gather.cc, src/kernels/kunlun/broadcast.cc, test/kernels/kunlun/test_kunlun_allgather.cc, test/kernels/kunlun/test_kunlun_broadcast.cc
=> MERGE xpu_allgather to xpu_xccl

include/cuda/cuda_split_concat.h, test/kernels/cuda/test_cuda_concat.cc, test/kernels/cuda/test_cuda_split.cc
=> support 8D tensor, add test example

CMakeLists.txt, Makefile, include/nnet/test.h, src/nnet/test.cc, test/nnet/test_OpSearch.cc, test/nnet/test_TConv2gemm.cc, test/nnet/test_conv2conv.cc, test/nnet/test_conv2gemm.cc, test/nnet/test_g2bmm.cc, test/nnet/test_memboundOp.cc, test/nnet/test_mutator.cc
打开 CUDA 有 5 个单测不过，不打开有 4 个——但很有可能是因为我没有 tvm 才不过的。
=> test: 支持编译 einnet 单元测试，但不是所有测试都能通过

include/core/kernel.h, include/utils/operator_utils.h, src/utils/operator_utils.cc
=> - modify error info when kernel not found

include/core/graph_handler.h, pyinfinitensor/src/pyinfinitensor/onnx.py, pyinfinitensor/tests/test_onnx.py, src/core/graph_handler.cc, test/kernels/cuda/test_cuda_split.cc
支持根据前端得到split算子的split属性，从而进行不等分split操作
=> fix Issue 187 split infershape wrong

include/core/graph_handler.h, pyinfinitensor/src/pyinfinitensor/onnx.py, pyinfinitensor/tests/test_onnx.py, src/core/graph_handler.cc, src/operators/resize.cc, test/kernels/cuda/test_cuda_resize.cc
=> add frontend resize kernel

src/kernels/cpu/reshape.cc, test/kernels/nativecpu/test_nativecpu_identity.cc
add reshape/identity/squeeze/flatten/unsqueeze op cpu kernel
=> feat: add reshape/identity/squeeze/flatten/unsqueeze op cpu kernel

docs/SUPPORT_MATRIX_CN.md, docs/USER_GUIDE_CN.md
=> fix broken link in docs

examples/distributed/README.md, examples/distributed/cuda_launch.py, examples/distributed/parallel_opt.py, examples/distributed/run_pytorch.py, include/cuda/cuda_element_wise.h, include/cuda/cuda_expand.h, pyinfinitensor/src/pyinfinitensor/onnx.py, src/kernels/cuda/element_wise.cc, src/kernels/cuda/element_wise.cu, src/kernels/cuda/expand.cu, src/kernels/cuda/matmul.cc
1. 改善分布式脚本
2. 添加pytorch运行脚本
3. where算子优化
4. pow和div算子优化
=> 针对bert和gpt2模型分布式推理的优化

src/kernels/kunlun/unary.cc
=> add kunlun squeeze kernel

pyinfinitensor/src/pyinfinitensor/onnx.py, src/kernels/cuda/pooling.cc, src/operators/pooling.cc
Accommodated the existing pooling operation to accept 1D pooling.
=> Accommodate avg pool1 d

.gitmodules
=> Removed submodule directory examples/NNmodel

CMakeLists.txt, include/core/common.h, include/core/graph.h, include/core/op_type.h, include/operators/slice.h, include/utils/data_convert.h, src/operators/squeeze.cc
Closes https://github.com/InfiniTensor/InfiniTensor/issues/277
=> Fix GCC13+ compatibility

include/core/data_type.h, pyinfinitensor/src/pyinfinitensor/onnx.py, src/operators/conv.cc
- Add 1D support for Conv and ConvTranpose2d
- Add != operator overload for DataType class
=> Renwu4 Front - Conv, ConvTranspose, and DataType != 
